# Generated by Django 3.2.4 on 2021-06-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='id',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='ipv4_addr',
            field=models.GenericIPAddressField(primary_key=True, serialize=False),
        ),
    ]
