# Generated by Django 3.2.4 on 2021-06-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210616_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='hostname',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='password',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='username',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
