# Generated by Django 3.2.4 on 2021-06-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210616_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='order_no',
            field=models.IntegerField(default=0),
        ),
    ]
