# Generated by Django 3.2.4 on 2021-06-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_inventory_order_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='ipv4_addr',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='hostname',
            field=models.CharField(default='default', max_length=15, primary_key=True, serialize=False),
        ),
    ]
