# Generated by Django 3.2.5 on 2021-11-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_playbookstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbookstatus',
            name='playbookprogress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playbookstatus',
            name='playbookstatus',
            field=models.IntegerField(choices=[(0, 'Not Play Yet'), (1, 'Succeed'), (2, 'Failed'), (3, 'Cancel')]),
        ),
        migrations.AlterField(
            model_name='playbookstatus',
            name='processid',
            field=models.IntegerField(null=True),
        ),
    ]
